### ISSUE TITLE
Symlinks converted to real directories

### ISSUE THREAD

**Issue by mrmekon** [abique/tmfs#16]
This project seems stagnant, but it's still very useful so I'll report for the record:

tmfs converted some directory symlinks into 'real' directories.  But not all of them, and I'm not sure how to tell what was different.

Specifically, `~/Library/Containers/com.apple.CalendarNotification.CalNCService/Data/` contains symlinks up to some of the user's data folders (`~/Downloads`, `~/Movies`, `~/Pictures`, `~/Music`), but became 'real' directories in the tmfs mount.  Those also tend to be where the bulk of a user's disk usage is.  This resulted in basically doubling the size of my backup when I rsync'd my home directory (and losing track of the symlinks, of course).

**Comment by abique** [comment]
Hi,
I don't have access to time machine file system anymore. But I'm happy to merge fixes ;-)
Alex.

**Comment by Muks14x** [comment]
I was just about to open an issue for the same thing. I was copying all my files recursively from a time machine backup and noticed that `~/Library/Containers/com.apple.CalendarNotification.CalNCService/Data/` contains a symlink to ~/Library, causing an infinite loop (since it was being copied as a new 'real' dorectory each time). I had to limit my copying depth to avoid this. This is also the same reason du crashes (Issue #4), I think - infinite loops.

**Comment by isundaylee** [comment]
I ran into this same issue, and did some digging. The issue happens when a symlink points to a ".HFS+ Private" directory. For example, from the HFS+ mount, `ls -l` gives:

```
root@mnas:.../Library/Containers/com.apple.iChat/Data# ls -lh
total 20K
lrwxr-xr-x        1  501 dialout  19 Oct  9  2014 Desktop -> ../../../../Desktop
-r--r--r-- 39402581 root 40542190  0 Apr  7  2015 Documents
lrwxr-xr-x        1  501 dialout  21 Oct  9  2014 Downloads -> ../../../../Downloads
drwx------        1  501 dialout  28 Nov 15  2016 Library
lrwxr-xr-x        1  501 dialout  18 Oct  9  2014 Movies -> ../../../../Movies
lrwxr-xr-x        1  501 dialout  17 Oct  9  2014 Music -> ../../../../Music
lrwxr-xr-x        1  501 dialout  20 Oct  9  2014 Pictures -> ../../../../Pictures
```

However, for the same folder in `tmfs`, `ls -l` gives (note that `Movies` is no longer shown as a symlink):

```
jiahaoli@mnas:.../Library/Containers/com.apple.iChat/Data$ ls -lh
total 16K
lrwxr-xr-x 1 jiahaoli jiahaoli 19 Oct  9  2014 Desktop -> ../../../../Desktop
drwx------ 1 jiahaoli jiahaoli  3 Oct  9  2014 Documents
lrwxr-xr-x 1 jiahaoli jiahaoli 21 Oct  9  2014 Downloads -> ../../../../Downloads
drwx------ 1 jiahaoli jiahaoli 28 Nov 15  2016 Library
drwx------ 1 jiahaoli jiahaoli  9 Jan 29  2017 Movies
lrwxr-xr-x 1 jiahaoli jiahaoli 17 Oct  9  2014 Music -> ../../../../Music
lrwxr-xr-x 1 jiahaoli jiahaoli 20 Oct  9  2014 Pictures -> ../../../../Pictures
```

I submitted a PR that fixes this by using `lstat` instead of `stat` in `get_real_path`.
